name: check_lint_rules_identity
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  file: ^7.0.0
  meta: ^1.11.0
  pub_semver: ^2.1.4
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.7
  lints: ^2.0.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  test: ^1.21.0
